# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7528b1cf2f94da91829f89b7775f17419c537d76bb8536984b88b8bc025c1d265850542d7cc33f1f973af936ae3328be7589230463db501f7fd27eb59340acb

test:
  secret_key_base: f259ef04ab8b77ec854026a25b853d5e18c8005006a1575cce9c34302c34a9d500e23f52fe53dac1cd386bce94befd0394a423072a278bedb196f609d09d6529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
